CREATE TABLE Brands(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(30),
	Created DATETIME NULL,
	Modified DATETIME NULL,
	IsActive BIT NOT NULL DEFAULT(1),
	IsDeleted BIT NOT NULL DEFAULT(0)
)

CREATE TABLE Stores(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(30) NOT NULL,
	Phone VARCHAR(14) NULL,
	ManagerId INT NOT NULL,
	Created DATETIME NULL,
	Modified DATETIME NULL,
	IsActive BIT NOT NULL DEFAULT(1),
	IsDeleted BIT NOT NULL DEFAULT(0)
)

CREATE TABLE Products(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(30) NOT NULL,
	BrandId INT,
	Price MONEY NOT NULL,
	Created DATETIME NULL,
	Modified DATETIME NULL,
	IsActive BIT NOT NULL DEFAULT(1),
	IsDeleted BIT NOT NULL DEFAULT(0),
	CONSTRAINT FK_Products_BrandId FOREIGN KEY(BrandId) REFERENCES Brands(Id)
)

CREATE TABLE Employees(
	Id INT PRIMARY KEY IDENTITY(1,1),
	FirstName VARCHAR(20) NOT NULL,
	LastName VARCHAR(20) NOT NULL,
	Email VARCHAR(30) NOT NULL,
	IsManager BIT NOT NULL,
	StoreId INT NOT NULL,
	Created DATETIME NULL,
	Modified DATETIME NULL,
	IsActive BIT NOT NULL DEFAULT(1),
	IsDeleted BIT NOT NULL DEFAULT(0),
	CONSTRAINT FK_Employees_Store FOREIGN KEY (StoreId) REFERENCES Stores(Id)
)

CREATE TABLE Warehouses(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(30) NOT NULL,
	ManagerId INT NOT NULL,
	Created DATETIME NULL,
	Modified DATETIME NULL,
	IsActive BIT NOT NULL DEFAULT(1),
	IsDeleted BIT NOT NULL DEFAULT(0)
	CONSTRAINT FK_WareHouses_Empoyee FOREIGN KEY (ManagerId) REFERENCES Employees(Id)
)

CREATE TABLE StoreWarehouses(
	Id INT PRIMARY KEY IDENTITY(1,1),
	StoreId INT NOT NULL,
	WarehouseId INT NOT NULL,
	Created DATETIME NULL,
	Modified DATETIME NULL,
	IsActive BIT NOT NULL DEFAULT(1),
	IsDeleted BIT NOT NULL DEFAULT(0)
	CONSTRAINT FK_StoreWareHouses_Store FOREIGN KEY (StoreId) REFERENCES Stores(Id),
	CONSTRAINT FK_StoreWareHouses_WareHouse FOREIGN KEY (WarehouseId) REFERENCES Warehouses(Id)
)

CREATE TABLE ProductWarehouses(
	Id INT PRIMARY KEY IDENTITY(1,1),
	ProductId INT NOT NULL,
	WarehouseId INT NOT NULL,
	Created DATETIME NULL,
	Modified DATETIME NULL,
	IsActive BIT NOT NULL DEFAULT(1),
	IsDeleted BIT NOT NULL DEFAULT(0),
	CONSTRAINT FK_ProductWarehouses_Products FOREIGN KEY (ProductId) REFERENCES Products(Id),
	CONSTRAINT FK_ProductWarehouses_Warehouses FOREIGN KEY (WarehouseId) REFERENCES Warehouses(Id)
)